### ISSUE TITLE
Version 0.2.0 is not published on nuget.org

### ISSUE THREAD

**Issue by manuc66** [wozzo/Cake.TeamCityCoverageReporter#8]
Hi,

The version `0.2.0`  does not appear on nuget.org and is not available from build script:

```
Preparing to run build script...
Running build script...
Error: Unable to find version '0.2.0' of package 'Cake.TeamCityCoverageReporter'.
```

Thanks

**Comment by gep13** [comment]
@manuc66 not entirely sure why this was the case, and I am sorry that I didn't see this until now.

Version 0.2.0 has just been pushed to NuGet.org.
